#%RAML 1.0 NamedExample

value:
   
   -
    ID: 1
    firstName : Cheater
    lastName: Idiot
    address: Erragadda
    postalCountry: INDIA
    miles: 1245
    creationDate: 2002-10-02T10:00:00-05:00
    accountType: Business
   
   -
    ID: 2
    firstName : Shuu
    lastName: Stupid
    address: chanchalguda
    postalCountry: FRANCE
    miles: 1239
    creationDate: 2002-10-02T10:00:00-05:00
    accountType: Personal